name: Deployment on server
on:
  push:
    branches:
      - master

jobs:
  deploy_master:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: Deploy Production
    runs-on: ubuntu-latest
    steps:
      - name: Connecting SSH And Executing Deployment Scripts
        uses: appleboy/ssh-action@master
        with:
          host: 159.65.145.104
          username: root
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCbu+WP+30S4L0It4ojwBmY4d4xZGKtHs8SW0CQ99zSVHoUGsiHRne+jpPtIHG1ikiRo3/6mC2zkapQfCVA6OjhmIbJuvktM/9vTwU+bTdTVyV5lhR5RE5oZGTahA0mOzy6kSNqzDIS8GStKHHZu472R5RljmNiggjyloig/ouVkRlZePkXrm8V6NZxilbc3BDaQaSWaL9uYOdVBYIp8n9cvreWSsh1MBHIPRPQoekWeQYXQuwI1sh/N0oZ2lZuhxnpw0UU5cuYbxGNdvGbiXFEpFxBW+dgsTfkFrolE1a0WXz5xM0X+Q4K1GQkzYw2vuH00Bbg0zLL/JyDC/RVYQyz0/g0lxH6XI+ExwTR5JwhYXKgWG2/iS23k6Hcgm3npTkkBDCu42O3o2WLhCm3MENYjirAgHz7r63xivNx1pRlnTLG+IbNqfNSWEXaysRmuinMmaI0paBxl0vwBT1Kfu+2RLQq05wI4IMD3OQOX2PyS0JORwStwok4f/e84EIZ0fk= root@ubuntu-s-2vcpu-4gb-blr1-01
          port: 22
          script: |
            cd /var/www/ease-dcr-backend
            git fetch --all
            git checkout master
            git reset --hard origin/master
            source ./env/bin/activate
            pip install -r requirements.txt
            pkill gunicorn || true
            pkill daphne || true
            gunicorn -b 0.0.0.0:8000 DCR.wsgi:application &
            daphne -b 0.0.0.0 -p 8001 DCR.asgi:application &
