name: Deployment on server
on:
  push:
    branches:
      - master

jobs:
  deploy_master:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: Deploy Production
    runs-on: ubuntu-latest
    steps:
      - name: Connecting SSH And Executing Deployment Scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/ease-dcr-backend
            git fetch --all
            git checkout master
            git reset --hard origin/master
            source ./env/bin/activate
            python3 manage.py makemigrations
            python3 manage.py migrate
